name: StrawHats

on:
  push:
    branches: [main, frontend]
  pull_request:
    branches: [main, frontend]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: frontend 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Add MongoDB repository
      run: |
        wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
        sudo apt-get update

    - name: Install MongoDB
      run: sudo apt-get install -y mongodb-org


    - name: Start MongoDB
      run: |
        sudo systemctl start mongod
        sudo systemctl status mongod

    # Run tests
    - name: Run tests
      run: |
        python3 backend/testing_app.py
