name: StrawHats

on:
  push:
    branches: [main, frontend]
  pull_request:
    branches: [main, frontend]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]
    
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --bind_ip_all --quiet
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: frontend 
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Wait for MongoDB to start
      run: |
        for i in {1..30}; do
          if nc -z localhost 27017; then
            echo "MongoDB is up!"
            break
          fi
          echo "Waiting for MongoDB..."
          sleep 1
        done

    - name: Run tests
      env:
        MONGO_URI: mongodb://localhost:27017/mydatabase
      run: |
        python3 backend/testing_app.py